using Biz.Morsink.Identity;
using Biz.Morsink.Rest.Metadata;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace Biz.Morsink.Rest
{
    /// <summary>
    /// Repository class for RestJobResults.
    /// </summary>
    public class JobResultRepository : RestRepository<RestJobResult>, IRestGet<RestJobResult, NoParameters>
    {
        private readonly IRestJobStore restJobStore;
        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="restJobStore">An IRestJobStore instance for retrieving RestJobs.</param>
        public JobResultRepository(IRestJobStore restJobStore)
        {
            this.restJobStore = restJobStore;
        }
        /// <summary>
        /// Gets a RestJobResult.
        /// </summary>
        /// <param name="id">The identity value of the RestJobResult.</param>
        /// <param name="parameters">No parameters.</param>
        /// <returns>An asynchronous Rest reponse that might contain a RestJobResult.</returns>
        public async ValueTask<RestResponse<RestJobResult>> Get(IIdentity<RestJobResult> id, NoParameters parameters, CancellationToken cancellationToken)
        {
            var res = await restJobStore.GetJob(id.Provider.Creator<RestJob>().Create(id.Value));
            if (res == null || res.Task.Status < TaskStatus.RanToCompletion)
                return RestResult.NotFound<RestJobResult>().ToResponse();
            else
                return Rest.Value(new RestJobResult(res)).ToResponse();
        }
        /// <summary>
        /// Process the reponse.
        /// A RestJobResult is not supposed to be the value of an actual successful result.
        /// Instead, the RestJob's response is sent if it is available.
        /// If the result is not available, or the RestJob could not be found, a NotFound result is returned.
        /// This might be somewhat ambiguous if the original response ended up in a NotFound result as well.
        /// </summary>
        /// <param name="response">The reponse as generated by the capability method.</param>
        /// <returns>A Rest response.</returns>
        public override async ValueTask<RestResponse> ProcessResponse(RestResponse response)
        {
            if (response.UntypedResult.AsSuccess()?.RestValue.Value is RestJobResult result)
            {
                var job = result.Job;
                if (job.Task.IsCompleted)
                    return await job.Task;
                else
                    return RestResult.Pending<object>(job).ToResponse().WithMetadata(new ResponseCaching { CacheAllowed = false, CachePrivate = true, StoreAllowed = false });
            }
            else
                return await base.ProcessResponse(response);
        }
    }
}
