using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace Biz.Morsink.Rest.AspNetCore.Problem
{
    /// <summary>
    /// A base class for an RF7807 Problem type.
    /// </summary>
    public class Problem
    {
        /// <summary>
        /// A URI reference that identifies the problem type.
        /// Dereferencing this URI should provide human-readable documentation for the problem type.
        /// </summary>
        public string Type { get; set; }
        /// <summary>
        /// A short, human-readable summary of the problem type.
        /// </summary>
        [Required]
        public string Title { get; set; }
        /// <summary>
        /// The HTTP status code generated by the origin server for this occurrence of the problem.
        /// </summary>
        public int? Status { get; set; }
        /// <summary>
        /// A human-readable explanation specific to this occurrence of the problem.
        /// </summary>
        public string Details { get; set; }
        /// <summary>
        /// A URI reference that identifies the specific occurrence of the problem. 
        /// It may or may not yield further information if dereferenced.
        /// </summary>
        public string Instance { get; set; }
    }
}
